app:
    resource: '@AppBundle/Controller/'
    type: annotation

##########################################
########   Routes Calendrier   ###########
##########################################

calendar:
    resource: "@CalendarBundle/Resources/config/routing.yml"
    prefix:   /

##########################################
###########   Routes ADMIN   #############
##########################################

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

##########################################
############   FosJSRoutung   ############
##########################################

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    prefix:   /

##########################################
##############   FosJUser   ##############
##########################################

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

