app:
    resource: '@AppBundle/Controller/'
    type: annotation

app_header:
    resource: "@AppBundle/Resources/config/routing/header.yml"
    prefix:   /header

##############################################
#                                            #
#                   GALLERY                  #
#                                            #
##############################################

app_gallery:
    resource: "@AppBundle/Resources/config/routing/gallery.yml"
    prefix:   /gallery

##############################################
#                                            #
#                 SUB GALLERY                #
#                                            #
##############################################

app_subgallery:
      resource: "@AppBundle/Resources/config/routing/subgallery.yml"
      prefix:   /subgallery

##############################################
#                                            #
#                 COMPONENT                  #
#                                            #
##############################################

app_component:
    resource: "@AppBundle/Resources/config/routing/component.yml"
    prefix:   /component

##############################################
#                                            #
#                COLLECTION                  #
#                                            #
##############################################

app_collection:
    resource: "@AppBundle/Resources/config/routing/collection.yml"
    prefix:   /collection



############################################################################################################


##########################################
########   Routes Calendrier   ###########
##########################################

calendar:
    resource: "@CalendarBundle/Resources/config/routing.yml"
    prefix:   /

##########################################
###########   Routes ADMIN   #############
##########################################

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

##########################################
############   FosJSRoutung   ############
##########################################

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    prefix:   /

##########################################
##############   FosJUser   ##############
##########################################

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

