about_index:
    path:     /
    defaults: { _controller: "AppBundle:About:index" }
    methods:  GET

about_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:About:show" }
    methods:  GET

about_new:
    path:     /new
    defaults: { _controller: "AppBundle:About:new" }
    methods:  [GET, POST]

about_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:About:edit" }
    methods:  [GET, POST]

about_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:About:delete" }
    methods:  DELETE
