component_index:
    path:     /
    defaults: { _controller: "AppBundle:Component:index" }
    methods:  GET

component_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Component:show" }
    methods:  GET

component_new:
    path:     /new
    defaults: { _controller: "AppBundle:Component:new" }
    methods:  [GET, POST]

component_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Component:edit" }
    methods:  [GET, POST]

component_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Component:delete" }
    methods:  DELETE
