
##############################################
#                                            #
#                   GALLERY                  #
#                                            #
##############################################

app_gallery:
    resource: "@AppBundle/Resources/config/routing/gallery.yml"
    prefix:   /gallery

##############################################
#                                            #
#                 SUB GALLERY                #
#                                            #
##############################################

app_subgallery:
      resource: "@AppBundle/Resources/config/routing/subgallery.yml"
      prefix:   /subgallery

##############################################
#                                            #
#                     ABOUT                  #
#                                            #
##############################################

app_about:
        resource: "@AppBundle/Resources/config/routing/about.yml"
        prefix:   /about

##########################################
##############   LIIP IMAGINE   ##########
##########################################

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"