AppBundle\Entity\Component:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ComponentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        prix:
            type: integer
            nullable: true
        description:
            type: text
            nullable: true

    lifecycleCallbacks: {  }
