AppBundle\Entity\SubGallery:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\SubGalleryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        sgallery:
            type: string
            length: 255

    manyToOne:
        gallery:
          targetEntity: AppBundle\Entity\Gallery
          joinColumn:
            name: gallery_id
            referencedColumnName: id
    lifecycleCallbacks: {  }
